apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-demo
  namespace: k8s-demo
  labels:
    name: k8s-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: k8s-demo
  template:
    metadata:
      labels:
        name: k8s-demo
    spec:
      containers:
      - name: k8s-demo
        image: 	registry.cn-hangzhou.aliyuncs.com/spriteagile/k8s-demo
        resources: 
          requests:
            cpu: 200m
            memory: 200Mi
          limits: 
            cpu: 1
            memory: 500Mi
        ports:
        - containerPort: 80
        imagePullPolicy: Always
---

kind: Service
apiVersion: v1
metadata:
  name: k8s-demo
  namespace: k8s-demo
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: k8s-demo